### ISSUE TITLE
load-metrics.rb gives output `/usr/bin/env: ruby: No such file or directory` with /etc/default/sensu EMBEDDED_RUBY=true

### ISSUE THREAD

**Issue by mateodelnorte** [sensu/sensu-community-plugins#1029]
Hi,

I'm running sensu with /etc/default/sensu having EMBEDDED_RUBY=true. When I attempt to run load-metrics.rb, I get output `/usr/bin/env: ruby: No such file or directory`. If I yum install ruby, which I don't want to do, (I'm on CentOS 7) I get a require error. 

Other checks (such as check-procs.rb) are working fine. 

Any ideas?

Thx

**Comment by mattyjones** [comment]
@mateodelnorte 
A couple of questions to start with:

Are you running the latest version of the check?
Can you run the check manually `/opt/sensu/embedded/bin/ruby load-metrics.rb`?

If you can run other ruby checks fine but not this one then there **may** be an issue with the check, try looking to make sure the first line of the load-metrics is identical to the other ruby checks that are working.

Post any output you get from the above questions as well and we can try and troubleshoot it some more.

**Comment by mateodelnorte** [comment]
Thanks for the quick response. 

I'm able to run manually: 
```
[root@nj1slog01 ~]# /opt/sensu/embedded/bin/ruby /etc/sensu/plugins/load-metrics.rb
nj1slog01.load_avg.one 0.00 1423964087
nj1slog01.load_avg.five 0.03 1423964087
nj1slog01.load_avg.fifteen 0.05 1423964087
```
and I'm getting the check directly from github via my ansible scripts: 
```
- name: install load-metrics
  get_url: 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/load-metrics.rb
    dest=/etc/sensu/plugins/load-metrics.rb
  notify:
    - restart sensu-client

- name: chmod load-metrics
  file: path=/etc/sensu/plugins/load-metrics.rb owner=sensu group=sensu mode=755
  notify:
    - restart sensu-client
```
